Random Forests are one of the ensemble models -> they combine multiple machine learning models to achieve significantly higher accuracy, robustness, and generalization than any single model, reducing errors, preventing overfitting, and creating more stable predictions by leveraging diverse model perspectives, making them ideal for complex problems

Ensemble Models :
 they combine multiple machine learning models to achieve higher accuracy, better robustness, and improved generalization than any single model,
effectively reducing errors, overfitting, and bias by leveraging the diverse strengths of different models for more reliable predictions, especially 
on complex problems

<h3>Titanic Survival<h3>

In [27]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [28]:
df = pd.read_csv('Titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [51]:
X = df[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']]
y = df['Survived']

In [31]:
# convertinf male and female values to 0's and 1's
X['Sex'] = X['Sex'].map({'male' : 0,'female' : 1}) #use X.loc so that you wont have any problem

C:\Users\ECSLAB 6\AppData\Local\Temp\ipykernel_12192\1938024925.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['Sex'] = X['Sex'].map({'male' : 0,'female' : 1})

In [52]:

X.loc[:, 'Age'] = X['Age'].fillna(X['Age'].median())
miss = X.isna().sum()
print(miss)

Pclass    0
Sex       0
Age       0
SibSp     0
Parch     0
Fare      0
dtype: int64

In [53]:
X.loc[:,'Sex'] = X['Sex'].map({'male' : 0,'female' : 1})
X.head()

   Pclass Sex   Age  SibSp  Parch     Fare
0       3   0  22.0      1      0   7.2500
1       1   1  38.0      1      0  71.2833
2       3   1  26.0      0      0   7.9250
3       1   1  35.0      1      0  53.1000
4       3   0  35.0      0      0   8.0500

In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [55]:
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [61]:
y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
acc

0.8044692737430168

In [64]:
print(f"Accuracy: {acc:.2f}")
print("\nClassification Report:\n", classification_rep)
"""The sklearn.metrics.classification_report function in the scikit-learn library generates a text summary of the main classification metrics (precision,
recall, F1-score, and support) for each class in a classification problem"""

Accuracy: 0.80

Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

'The sklearn.metrics.classification_report function in the scikit-learn library generates a text summary of the main classification metrics (precision,\nrecall, F1-score, and support) for each class in a classification problem'

In [78]:
sample = X_test.iloc[0:1]
prediction = clf.predict(sample)

In [80]:
sample_dict = sample.iloc[0].to_dict()
print(sample_dict)
print(f"\nSample Passenger: {sample_dict}")
print(f"Predicted Survival: {'Survived' if prediction[0] == 1 else 'Did Not Survive'}")

{'Pclass': 3, 'Sex': 0, 'Age': 28.0, 'SibSp': 1, 'Parch': 1, 'Fare': 15.2458}

Sample Passenger: {'Pclass': 3, 'Sex': 0, 'Age': 28.0, 'SibSp': 1, 'Parch': 1, 'Fare': 15.2458}
Predicted Survival: Did Not Survive